# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=50)),
                ('comment', models.TextField(max_length=250)),
            ],
        ),
    ]
