# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_testplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tester',
            field=models.TextField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcase',
            name='comment',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('NR', 'Not Run'), ('PA', 'PASS'), ('FA', 'FAIL'), ('BL', 'BLOCKED'), ('NI', 'Not Implemented')], default='NR', max_length=2),
        ),
    ]
