# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('revision', models.CharField(max_length=200)),
                ('bmc_hostname', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('use', models.CharField(max_length=200)),
                ('processors_number', models.CharField(max_length=200)),
                ('silicon_rev', models.CharField(max_length=200)),
                ('tdp', models.CharField(max_length=200)),
                ('mem_config', models.CharField(max_length=200)),
                ('pci', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('pxe', models.CharField(max_length=200)),
                ('dvd', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('wombat_ip', models.CharField(max_length=200)),
                ('rpi', models.CharField(max_length=200)),
                ('pdu_info', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('bmc_version', models.CharField(max_length=200)),
                ('bmc_ip', models.CharField(max_length=200)),
            ],
        ),
    ]
